### ISSUE TITLE
increase max number of files

### ISSUE THREAD

**Issue by BlackIkeEagle** [Parchive/par2cmdline#11]
the README states that one can create "up to 32768 files". This seems to be because the maximum size of the block count is 32768 (16-1bit).. can the memory structure be pushed up towards 64bit for many files?

**Comment by ifsnop** [comment]
I have the same question. Why is 32767 the limit? Altering the source code so 64k is possible seems to work (I'm testing it myself right now)

**Comment by mdnahas** [comment]
I designed Par2 and I actually wanted it only to accept 1 file.  I figured support for many files could be better done by using "tar" or another Unix command-line tool.  Support for multiple files was for backwards compatibility.

If we do a redesign for "Par3", this may get changed.
