### ISSUE TITLE
Failing to recognize large files (Windows x64)

### ISSUE THREAD

**Issue by rwtodd** [Parchive/par2cmdline#127]
I noticed that, on Windows (x64 build targeting Win10), `par2 create large.file` would give me the following error on large (>2GB) files:

> You must specify a list of files when creating.

I changed DiskFile::FileExists and DiskFile::GetFileSize to use _stat64 directly, and the problem cleared up for me.  I only tested the x64 build... not sure if this breaks the 32-bit build or not.   I did check that I can use the resulting par2 files to `verify` on both windows and Linux.

Here were my changed functions, in case it helps:

~~~~~~
bool DiskFile::FileExists(string filename)
{
  struct _stat64 st;
  return ((0 == _stat64(filename.c_str(), &st)) && (0 != (st.st_mode & S_IFREG)));
}
~~~~~~

...and...

~~~~~~
u64 DiskFile::GetFileSize(string filename)
{
  struct _stat64 st;
  if ((0 == _stat64(filename.c_str(), &st)) && (0 != (st.st_mode & S_IFREG)))
  {
    return (u64)st.st_size;
  }
  else
  {
    return 0;
  }
}
~~~~~~

**Comment by mdnahas** [comment]
This seems odd.  The code currently uses _stat**i**64.  The change to _stat64 should not change things.

_stati64 uses 64-bit file lengths, just like _stat64.

The documentation says the difference is in file timestamps.  _stati64 sometimes use 32-bit timestamps, while _stat64 always uses 64-bit timestamps.

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/stat-functions?view=vs-2019

I'm going to push code that fixes a problem we had when blocksize exceeded 4GB.  Is it possible that that was the problem you had and you fixed it by different command-line options that changed the blocksize?

**Comment by rwtodd** [comment]
> This seems odd. The code currently uses _stat**i**64. The change to _stat64 should not change things.

DiskFile::FileExists uses a bare stat(), which expands to _stat64i32() on my system.  This fails for me on large files (returns -1).  On a fresh checkout, I verified that changing it so _stati64 works just as sell as _stat64.

It looks like GetFileSize() did not need to be changed, as you have already pointed out. When I was playing with it in January, I had changed them both to force 64-bit timestamps in case it mattered.

**Comment by mdnahas** [comment]
@rwtodd Just so you get credit, can you change FileExists to use _stati64, just like GetFileSize, and submit a pull request?  I believe I can approve the change on GitHub.

If you're not proficient with GitHub, I think I have enough to make the change.  (Although, I can only test with MinGW.)

**Comment by rwtodd** [comment]
Sure, no problem.  I've created the pull request.  I'll close the issue now--thanks for your help, and for continuing work on par2cmdline. It's a great tool.
