### ISSUE TITLE
[0.8.1] syntax error in tests (tests/test*: 10: [: !=: unexpected operator)

### ISSUE THREAD

**Issue by jcfp** [Parchive/par2cmdline#141]
Leaving the 'which wine' part unquoted in ```elif [ `which wine` != "" ] && [ -f "$execdir/par2.exe" ]``` causes a syntax error whenever 'wine' isn't available on the PATH.

**Comment by jcfp** [comment]
Patched in debian, see [here](https://salsa.debian.org/jcfp-guest/par2cmdline/blob/cdd0cfa4077ec08f6eaba10e5875d17ea6279654/debian/patches/02_fix_syntax_error_in_tests.diff).

**Comment by mdnahas** [comment]
I introduced that bug.  What's the issue?  Is `which wine` returning an error code and, therefore, the string comparison doesn't work?  

Also, it looks like `which doesnotexist` and "`which doesnotexist`" return different string when run in /bin/sh on my machine.  (Ubuntu 19.10).

You can test it on your /bin/sh with:
  echo start "`which doesnotexist`" end
  echo start `which doesnotexist` end

**Comment by jcfp** [comment]
Without quotes, if _which_ doesn't find anything the string to compare against goes missing, resulting in invalid syntax:
```
$ /bin/sh -c '[  != "" ]'
/bin/sh: 1: [: !=: unexpected operator
```
vs. `$ /bin/sh -c '[ "" != "" ]'` that doesn't have that problem. A similar problem occurs if _which_ does find the command it's looking for, but that just happens to be on a path that includes a space (/usr/local/my wine install/...).

The reason you get different results for your _echo_ invocations is due to lack of quoting as well. The proper comparison (resulting in identical output) would be these two:
```
echo "start `which doesnotexist` end"
echo "start \"`which doesnotexist`\" end"
```
Without those quotes at the beginning and end, _echo_ receives multiple arguments rather than a single one and prints each with a single space inbetween:
```
$ echo test   more                       spaces
test more spaces
```

**Comment by BlackIkeEagle** [comment]
this is probably because we have assumed default shell as bash, so it did not come up on my machine as an error and did not fail in travis either because of this. Would you be so kind to offer the debian patch as a PR @jcfp ?

**Comment by mdnahas** [comment]
@BlackIkeEagle All the scripts should have #!/bin/sh at the top, forcing the original Borne shell.

@jcfp It looks like you know more about strings in scripts than me.  (I've been doing it for a while, but I'm certainly no expert.)  Thanks for catching this.

If @jcfp can make the pull request, I'll test it on my Ubuntu machine.

**Comment by BlackIkeEagle** [comment]
@mdnahas I know, but /bin/sh can be bash or can be dash or something else. Hence I think we have a bashisism or something that bash deals with in a different way compared to dash for example.

We should use the quotes anyway

**Comment by mdnahas** [comment]
@BlackIkeEagle Wow, I never knew that.  I always assumed /bin/sh was the Bourne shell.  I've read a bit and the Bourne shell isn't even maintained anymore!  /bin/sh should get a POSIX-compatible shell.  (It sounds like other shells, when run as /bin/sh, enter a POSIX-compatible mode.)  Thanks for teaching me something new!
