### ISSUE TITLE
Core dump on single letter file name

### ISSUE THREAD

**Issue by kwloafman** [Parchive/par2cmdline#145]
Could be the short contents?  Or the short file name?

> $ echo -n 'hello' > a
$ par2 c -r10 -n1 a
.
Block size: 4
Source file count: 1
Source block count: 2
Recovery block count: 1
Recovery file count: 1
.
Opening: a
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 1) >= this->size() (which is 1)
Aborted (core dumped)
$ echo $?
134

**Comment by kwloafman** [comment]
It only crashes on the short filename, not the short contents.

**Comment by mdnahas** [comment]
My guess is that there is faulty logic when it tries to strip the filename extension.  

Is this problem impacting you?  If not, I'm willing to wait on fixing this issue.

**Comment by kwloafman** [comment]
No problem.  Found during testing duplicity.  I think the issue should stay open, but put it on the back burner.  I fixed the test cases to use longer filenames so it no longer affects me.

**Comment by mdnahas** [comment]
Yes, I agree.

Thanks for finding bugs for us!
