### ISSUE TITLE
0.6.11 configure.ac: add AC_CONFIG_MACRO_DIRS and LT_INIT

### ISSUE THREAD

**Issue by jaalto** [Parchive/par2cmdline#42]
Here is a small patch to update build for latest atutools

    From 1a12963388b18596010edfb9c479f3fcf9267a22 Mon Sep 17 00:00:00 2001
    From: Jari Aalto <jari.aalto@cante.net>
    Date: Sun, 15 Feb 2015 08:31:09 +0200
    Subject: [PATCH] configure.ac: add AC_CONFIG_MACRO_DIRS and LT_INIT
    Organization: Private
    Content-Type: text/plain; charset="utf-8"
    Content-Transfer-Encoding: 8bit

    Signed-off-by: Jari Aalto <jari.aalto@cante.net>
    ---
     configure.ac | 3 +++
     1 file changed, 3 insertions(+)

    diff --git a/configure.ac b/configure.ac
    index 24a5917..e859b77 100755
    --- a/configure.ac
    +++ b/configure.ac
    @@ -25,6 +25,9 @@ AC_PREREQ(2.58a)
     AC_INIT([par2cmdline], [0.6.11], [ike.devolder@gmail.com])
     AC_CONFIG_SRCDIR([par2cmdline.cpp])

    +AC_CONFIG_MACRO_DIRS([m4])
    +LT_INIT
    +
     AC_CANONICAL_HOST

     AC_CONFIG_HEADERS([config.h])
    --
    2.1.4

**Comment by BlackIkeEagle** [comment]
could you be more clear where this is an issue, I have no issues at all with the latest autconf/automake(2.69/1.15)

**Comment by BlackIkeEagle** [comment]
closing due to no reponse
