### ISSUE TITLE
Scanning extra files messes  up verification

### ISSUE THREAD

**Issue by ensisoft** [Parchive/par2cmdline#49]
Say you have the following files in a folder and foobar.mp3 is damaged and repairable.

foobar.par2
foobar.vol0+1.par2
foobar.mp3

invoke par2 like this: 
$ par2 r foobar.par2 ./*

The repair process will rename foobar.mp3 to foobar.mp3.1, but since foobar.mp3 is in the extrafiles list the process then will then fail with an ioerror. 

I have a fix for this where targets are removed from extrafiles list if they are duplicated there.

**Comment by BlackIkeEagle** [comment]
thanks
