### ISSUE TITLE
Extra files may be ignored during recovery attempts

### ISSUE THREAD

**Issue by Phaneron** [Parchive/par2cmdline#53]
##### Bug: Extra files with names containing the base name of a target file are ignored during recovery attempts

**Test case:**
1. generate a sample file with 2000 random bytes
2. create a par2 recovery file with 1000 bytes block size (2 source blocks) but no recovery blocks
3. Split the original file into two parts of 1000 bytes
4. remove the original file
5. try to recover the original file from the par2 recovery file and the two 'split files' as extra files

    dd bs=1000 count=2 if=/dev/random of=myfile.dat
    par2 c -s1000 -c0 myfile.dat
    dd bs=1000 count=1 if=myfile.dat of=myfile.dat.001
    dd bs=1000 count=1 skip=1 if=myfile.dat of=myfile.dat.002
    rm myfile.dat
    par2 r myfile.dat.par2 myfile.dat.001 myfile.dat.002

Even all data blocks are present in the extra files, par2cmdline fails to repair the target file because the first extra file is (silently) ignored during the recovery process.

**Bug analysis:**

    /* Code snippet from 'par2repairer.cpp', function Par2Repairer::VerifySourceFiles() */
    // What filename does the file use
    const std::string& file = sourcefile->TargetFileName();
    const std::string& name = DiskFile::SplitRelativeFilename(file, basepath);

    // if the target file is in the list of extra files, we remove it
    // from the extra files.
    list<CommandLine::ExtraFile>::iterator it = extrafiles.begin();
    for (; it != extrafiles.end(); ++it)
    {
      const CommandLine::ExtraFile& e = *it;
      const std::string& file = e.FileName();
      if (file.find(name) != std::string::npos)
      {
        extrafiles.erase(it);
        break;
      }
    }
	
The code above is supposed to remove an extra file that is identical with the target file.
	
But the check for identical file names is done in a wrong way: the extra file is discarded if the base name (without path) of the target file matches a substring in the full path of the extra file name.

This bug was introduced by the [commit](https://github.com/ensisoft/par2cmdline/commit/4ee6e3034720c8ebad7e24e727a04f32b9b1712d) for [Issue #49] (https://github.com/Parchive/par2cmdline/issues/49).

For a correct result the 'canonical' target path should be compared with the 'canonical' extra file path:

    // What filename does the file use
    const std::string& file = sourcefile->TargetFileName();
    const std::string& name = DiskFile::SplitRelativeFilename(file, basepath);
    const std::string& target_pathname = DiskFile::GetCanonicalPathname(file);

    // if the target file is in the list of extra files, we remove it
    // from the extra files.
    list<CommandLine::ExtraFile>::iterator it = extrafiles.begin();
    for (; it != extrafiles.end(); ++it)
    {
      const CommandLine::ExtraFile& e = *it;
      const std::string& extra_pathname = e.FileName();
	  // the string returned by ExtraFile member function 'FileName()' is
	  // a full pathname from a call to GetCanonicalPathname()
      if (!extra_pathname.compare(target_pathname))
      {
        extrafiles.erase(it);
        break;
      }
    }

**Comment by BlackIkeEagle** [comment]
Thanks, I'll test this in a week or two, currently I cannot test.

It would be nice if you could create a pull request for this.
