### ISSUE TITLE
par2cmdline producing incompatible par2 files on certain OpenBSD versions

### ISSUE THREAD

**Issue by kucharskim** [Parchive/par2cmdline#55]
Hi,

par2cmdline stopped working properly between OpenBSD 5.5 and 5.6. Newest version of OpenBSD as of today is 5.8-beta and OpenBSD is still at par2cmdline 0.4 in their packages repository and nothing in changed that package from OpenBSD 5.5. It looks that something changed in OpenBSD between version 5.5 and 5.6 that affected par2cmdline. When I say par2cmdline stopped working it constantly gives `Main packet not found.` when executed on main par2 file and fails immediately.

I've compiled par2cmdline 0.6.13 on OpenBSD 5.6 and 5.8-beta and par2cmdline is able to find main packet and is able to correctly verify the set of files. I've bisected the par2cmdline git repo and commit 4a4179f1e42bc11bbcc9d24554690d3bc5c31b38 fixes par2cmdline 0.4 verification issue on OpenBSD 5.6 and above.

However par2cmdline 0.6.13 on OpenBSD 5.6+ is not able to repair file sets created with par2cmdline 0.4 on OpenBSD 5.5 and earlier versions. par2cmdline 0.6.13 on OpenBSD 5.6+ is also not able to repair file sets created with other par2 software like QuickPar.

Another problem I've also noticed is that par2 files created on OpenBSD 5.6+ with par2cmdline 0.6.13 cannot be repaired with par2cmdline 0.4 on OpenBSD 5.5.

I have created example file distribution of files created with par2cmdline 0.4 on OpenBSD 5.5 and par2cmdline 0.6.13 on OpenBSD 5.6 if you would like to have a look.

Both OpenBSD are amd64. I'm not sure what additional info I need to provide.

**Comment by kucharskim** [comment]
In short, par2cmdline 0.4 in OpenBSD 5.5 and par2cmdline 0.6.13 compiled on OpenBSD 5.6+ are able to verify each others file sets, but are not able to repair each others file sets.

**Comment by kucharskim** [comment]
My test file sets are available [here](http://www.openbsd.to/pub/par2cmdline/), if someone would like to have a look.

**Comment by BlackIkeEagle** [comment]
so this can be closed, thanks
