### ISSUE TITLE
Allow the setting of basepath so repair files can be stored outside basedirectory

### ISSUE THREAD

**Issue by cowai** [Parchive/par2cmdline#61]
I want to put my .par2 files in a separate folder and not in the same as the source file.

How can I accomplish this?

```shell
$ cd /tmp/par2test
$ par2 create -r10 -n1 tray.css.part2  "/mnt/data/backups/Downloads/app/views/css/tray.css"
Ignoring out of basepath source file: /mnt/data/backups/Downloads/app/views/css/tray.css
You must specify a list of files when creating.

**Comment by BlackIkeEagle** [comment]
Currently this is not supported

**Comment by BlackIkeEagle** [comment]
changed the subject from "Ignoring out of basepath source file" ...

**Comment by cowai** [comment]
Ah I see. I would really appreciate this feature as I want to be able to script to have a separate tree of the folder structure where only the repair files is put. That way I dont need to polute my san with repair files.

**Comment by c89williams** [comment]
Thank you for implementing this!!!

**Comment by malhal** [comment]
This bug is back:

```
ubuntu@venus:~/itunes/downloads$ par2 c -n1 zips/pars/2016-09-29.zip zips/2016-09-29.zip 
Ignoring out of basepath source file: /home/ubuntu/itunes/downloads/zips/2016-09-29.zip
You must specify a list of files when creating.
```

**Comment by BlackIkeEagle** [comment]
@malhal there was not yet a release with the fix in it, I must find some time to finish a 0.7.0 release

**Comment by malhal** [comment]
FYI I worked around this by copying the par2 executable 0.4 from an Ubuntu 12 install, now my scrips are running again on Ubuntu 16.
