### ISSUE TITLE
tests failing

### ISSUE THREAD

**Issue by andrew-hill** [Parchive/par2cmdline#66]
tests 12, 13 and 18 fail for me on my NAS (ReadyNAS OS6)

it's the "`status=none`" parameter that breaks the test in the call to `dd`, e.g. from test12:

    dd if=test.data-correct bs=113579 count=1 status=none of=test.data

my version of `dd` (coreutils 8.13) does support `status=noxfer`, but not `status=none`, and the `status` operand is apparently entirely unrecognised on Mac OS X's built-in `dd`

perhaps the status ought to be removed (and the output piped to `/dev/null` if it's actually a problem?)

**Comment by BlackIkeEagle** [comment]
I'll just remove the status parts, there is actually no need for it
