### ISSUE TITLE
Very slow performance over NFS

### ISSUE THREAD

**Issue by lucaspiller** [Parchive/par2cmdline#71]
Performance of par2 is very slow when running over NFS. I'm wondering if there is anything that can be done in the application to speed it up.

As an example, I have a directory with 80MB of par2 files:

```
$ ls -l
total 80932
-rw-r--r-- 1 luca luca    59508 Jul 14 09:28 153222.par2
-rw-r--r-- 1 luca luca  5540336 Jul 14 09:28 153222.vol000+01.par2
-rw-r--r-- 1 luca luca 11080576 Jul 14 09:28 153222.vol001+02.par2
-rw-r--r-- 1 luca luca 22101644 Jul 14 09:28 153222.vol003+04.par2
-rw-r--r-- 1 luca luca 44084368 Jul 14 09:28 153222.vol007+08.par2
$ du -sh
80M .
```

When performing the verify operation on the host it runs fast:

```
$ time par2verify -q 153222
Loading "153222.par2".
Loading "153222.vol000+01.par2".
Loading "153222.vol001+02.par2".
Loading "153222.vol003+04.par2".
Loading "153222.vol007+08.par2".
Loading "153222.par2".
...
Repair is required.
Repair is not possible.
You need 1959 more recovery blocks to be able to repair.

real    0m6.193s
user    0m6.152s
sys 0m0.040s
```

But the same operation over NFS is very slow:

```
$ time par2verify -q 153222.par2
Loading "153222.par2".
Loading "153222.vol000+01.par2".
Loading "153222.vol001+02.par2".
Loading "153222.vol003+04.par2".
Loading "153222.vol007+08.par2".
Loading "153222.par2".
...
Repair is required.
Repair is not possible.
You need 1959 more recovery blocks to be able to repair.

real    3m23.342s
user    0m6.236s
sys 0m0.180s
```

The NFS client in this case is an Ubuntu VM running under KVM, where the VM host is also the NFS host - so everything goes over the internal network. Other operations over NFS (e.g. extracting archives) aren't anywhere near as slow, so I don't think it is anything inherently wrong with my NFS setup - maybe there are some parameters that can be tweaked to optimise the way par2 accesses files?

**Comment by BlackIkeEagle** [comment]
I should have a look at that, I guess there are some operations par2 does nfs does not like.

**Comment by BlackIkeEagle** [comment]
I don't think it will be possible to improve the performance on nfs that much, there is too much going on on the disk to be fast over nfs
