### ISSUE TITLE
par2 spec -- recovery slice volume name

### ISSUE THREAD

**Issue by thezoggy** [Parchive/par2cmdline#73]
per par spec: http://parchive.sourceforge.net/docs/specifications/parity-volume-spec/article-spec.html#i__134603784_890

`PAR 2.0 files should always end in ".par2". For example, "file.par2". If a file contains recovery slices, the ".par2" should be preceded by ".volXX-YY" where XX to YY is the range of exponents for the recovery slices. For example, "file.vol20-29.par2". More than 2 digits should be used if necessary. Any exponents that contain fewer digits than the largest exponent should be preceded by zeros so that all filenames have the same length. For example, "file.vol075-149.par2". Exponents should start at 0 and go upwards.`

source mentions both formats:
https://github.com/Parchive/par2cmdline/blob/master/par2repairer.cpp#L715

but when creating, it does `+`:
https://github.com/Parchive/par2cmdline/blob/master/par2creator.cpp#L729

looking back at initial commit from 1.0, it was `+` as well:
https://github.com/Parchive/par2cmdline/commit/856eed8a736e78ffbaba7a8f56c3f37c2fd74de1#diff-b594972881837aa55267474e0b1378bfR598

I personally have only seen `+` being used since majority of things are created with par2cmdline.. 
but other apps use `-` not `+` which is technically correct per spec...  so not sure if you have the capability but probably should update spec to reflect that `-` or `+` is fine to use in the filename?

**Comment by BlackIkeEagle** [comment]
@thezoggy Sorry I can't update the spec documentation on sourceforge.
