### ISSUE TITLE
Basepath

### ISSUE THREAD

**Issue by Safihre** [Parchive/par2cmdline#77]
Reported by a user who build par2cmdline from source and I can also reproduce it, used the latest version here on git.

I load the file ```/media/sf_Complete/TEST/5dd91986e04825bcc9efdfa1e33a9011f5a07f69.vol003+04.par2 ``` and then tell it to also scan the file in the same folder ```/media/sf_Complete/TEST/2ddc9967e0379b8db3a8d51e5a1383339bd19672```.
Why is that "out of basepath"?

```sh
~/Documents/par2cmdline$ ./par2 v /media/sf_Complete/TEST/5dd91986e04825bcc9efdfa1e33a9011f5a07f69.vol003+04.par2 /media/sf_Complete/TEST/2ddc9967e0379b8db3a8d51e5a1383339bd19672
Ignoring out of basepath source file: /media/sf_Complete/TEST/2ddc9967e0379b8db3a8d51e5a1383339bd19672
Loading "5dd91986e04825bcc9efdfa1e33a9011f5a07f69.vol003+04.par2".
```

**Comment by sdettmer** [comment]
Hi,

if I understand sources correctly, "out of basepath" means that a file is not in the basepath - or par2 thinks so. I think here the absolute path causes this. Does it work with relative paths?
The basepath defaults to the current directory ("."). There is a command line option to specify another directory:

`  -B<path> : Set the basepath to use as reference for the datafiles`

I think you could use it and call:

`./par2 v -B/media/sf_Complete/TEST/ /media/sf_Complete/TEST/5dd91986e04825bcc9efdfa1e33a9011f5a07f69.vol003+04.par2 /media/sf_Complete/TEST/2ddc9967e0379b8db3a8d51e5a1383339bd19672`

but as I could not reproduce the exact behavior, I couldn't test but only guess.

Hope it helps.

**Comment by Safihre** [comment]
Non-relative didn't change:
```
~/Documents/par2cmdline $ par2 v /media/pi/Saf/TEST/5dd91986e04825bcc9efdfa1e33a9011f5a07f69.vol003+04.par2 /media/pi/Saf/TEST/013312757d5bd35bdf82e2c7732024dcd5664a15 
Ignoring out of basepath source file: /media/pi/Saf/TEST/013312757d5bd35bdf82e2c7732024dcd5664a15
Loading "5dd91986e04825bcc9efdfa1e33a9011f5a07f69.vol003+04.par2".
```
My question is kind of more: why does it care about a basepath at all?

**Comment by BlackIkeEagle** [comment]
@Safihre It cares about the basepath

**Comment by BlackIkeEagle** [comment]
@Safihre you would rather have the previous behaviour restored? I see that you already built in the -B detection in sabnzbd.

**Comment by Safihre** [comment]
I guess I was just surprised why par2 was trying to be smarter than me, when I specifically tell it to scan certain files, it thinks it knows better and doesn't scan them.. 
But I understand the considerations and indeed we have fixed it now in sabnzbd. 

PS: would be nice to have another Windows release! We now have to do some workarounds for it because it refuses to scan `.001` files, which I believe is fixed in newer versions.

**Comment by BlackIkeEagle** [comment]
@Safihre I'll have to check if I can find some windows to build it on. I'm going to try to get 0.7.0 out ASAP now

**Comment by Safihre** [comment]
There are free windows VM images available by Microsoft for this exact purpose :) 
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by Safihre** [comment]
Or: maybe try using Appveyor? We now also use it for our Windows builds and it works great!

**Comment by malhal** [comment]
I just updated from Ubuntu 16.04 to 18.04 and now facing this error I didn't get before. Seems like it's related to this issue.

```
ubuntu@x:~/downloads$ par2 -V
par2cmdline version 0.8.0
ubuntu@x:~/downloads$ par2 c -n1 zips/pars/2023-01-01.zip zips/2023-01-01.zip 
Ignoring out of basepath source file: /home/ubuntu/downloads/zips/2023-01-01.zip
You must specify a list of files when creating.
```
