### ISSUE TITLE
Command line  "-r<c><n>" and "-n<n>" don't work together

### ISSUE THREAD

**Issue by sdettmer** [Parchive/par2cmdline#80]
When using for example:

   `par2 c -v -a "$(basename $(pwd))" -s128000 -rm20 -n2 *.JPG`

the following error message appears:

  `Cannot set file count when redundancy is set to 0.`

apparently from `commandline.cpp:537`. When using "-r20" instead or omitting -n2, it works.

Why shouldn't it be possible to set the file count when using `-rm` instead of `-r`? Man page tells, `-c` cannot be used with it, which makes a lot of sense, but code also checks it.

man page also tells `don't use both -b and -s`, but why? Specifying both would allow to omit `-r`.

**Background why I tried these parameters:**

I have folders with varying number of JPG files and would like to automate my PAR2 file generation. I would like to ensure recovering (at least) 2 files regardless of the number of JPG files (can be only 2 or up to 1000 per folder). Also I would have at least 2% redundancy. As result I want 2 files in "power of 2 scheme". If a JPG is less than 10 MB, `-rm20 -n2` (and if it would be supported another `-r2`) would be my options, but they don't work.

**Comment by sdettmer** [comment]
I think I fixed it.
Seems this option combination was simply never used, so no one noticed it, I just had to change the handling of the variable recoveryfilecount and remove blocking the option -n (to set recoveryfilecount).
I hope the change is easy enough not to break anything (make check still PASS of course), but please review my change and the comment in the code.

If you like any improvements to the patch, please don't hesitate to tell me what you like to have changed.

I added a test for it. The script is tests/test5rk - which is like test5, but with -rk option, hence the name. Please just tell if you like test25 better, then I can change it.

**Comment by sdettmer** [comment]
Thank you for merging! 
Should I do something with this issue, such as testing / closing it?

**Comment by BlackIkeEagle** [comment]
It look ok so closing
