### ISSUE TITLE
0.7.0 Windows release won't run: VCOMP140.DLL is missing

### ISSUE THREAD

**Issue by Safihre** [Parchive/par2cmdline#94]
![image](https://cloud.githubusercontent.com/assets/5703454/25177851/ba4641d4-2503-11e7-9b04-dd1aa72bfef6.png)
Seems to be part of 2015 C++ redistributable, but this does not happen in the 0.6.13 release.

**Comment by BlackIkeEagle** [comment]
It was built on windows 10 with visualstudio 2017 in the "winxp" compatibility mode. Since I'm not really a windows user I have no clue here.

Does it work on windows 10 ?

**Comment by Safihre** [comment]
I am on Windows 10 x64. Through Google I find that you have to specify in the project that these dependencies need to be merged in. 
But I never used visual studio so can't say more than what Google told me

**Comment by BlackIkeEagle** [comment]
ok I'll check it out, thanks

**Comment by BlackIkeEagle** [comment]
I can't seem to merge the dependencies in, the common solution I find is that you have to install the vc redist package for your architecture to make it work https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by Safihre** [comment]
So this trick doesn't work? 
http://stackoverflow.com/a/32999084

**Comment by BlackIkeEagle** [comment]
@Safihre I think I tried it, but I'm not sure anymore, I've tried a whole bunch of things that did result in the same error

I'll try again this evening

**Comment by BlackIkeEagle** [comment]
Its already set to /MT for release, so no its not working the suggestion :)

**Comment by BlackIkeEagle** [comment]
Ok I changed the approach, I'm cross compiling for windows using mingw-w64 now. that way I can produce completely standalone par2.exe binaries.

**Comment by Safihre** [comment]
Perfect :+1:

**Comment by BlackIkeEagle** [comment]
0.7.1 is released

**Comment by Safihre** [comment]
Oh wow, the `par2.exe` is now 13.000kb, while it was around 300kb of par2cmdline 0.6.13.. That's a 43 fold increase. How did you build 0.6.14? Since it did not have the redistributable installation requirement.

**Comment by BlackIkeEagle** [comment]
I did not build any windows binaries before 0.7, so I have no idea

**Comment by Safihre** [comment]
@thezoggy, maybe you know how to build the Windows `exe` with reasonable file size but without requiring the `2015 C++ redistributable`?

**Comment by thezoggy** [comment]
when you compile, use: `-Os`
that will remove symbol files and optimize for file size

**Comment by BlackIkeEagle** [comment]
ok added mingw strip, that reduces the filesize of the par2.exe to  ~1,5Mb

**Comment by Safihre** [comment]
@thezoggy were you able to compile it on your PC and get it smaller? 
I tried, but was not successful with the whole Visual Studio dependency system to get the right compilers.

**Comment by thezoggy** [comment]
@Safihre black already figured out how to strip the symbols, he just does it post compile with strip.exe. 
which you could just do yourself if you wanted 0.7.1 right now: `/usr/x86_64-w64-mingw32/bin/strip par2.exe`

**Comment by Safihre** [comment]
Isn't 1.5MB still large? The current one is 294KB...

**Comment by war59312** [comment]
Good to read: https://stackoverflow.com/questions/26103966/how-can-i-statically-link-standard-library-to-my-c-program

And: https://stackoverflow.com/questions/1993390/static-linking-vs-dynamic-linking

**Comment by BlackIkeEagle** [comment]
If you want smaller than ~1,5Mb binaries you will have to get me a windows guru, whatever setting I changed in visual studio it keeps asking for VCOMP140.DLL, and the static linking with gcc gives 1,5Mb binary, I'm not going to change -O3 to -Os since -O3 should be better for performance

**Comment by animetosho** [comment]
VCOMP*.DLL is the Visual C++ OpenMP runtime. Unfortunately, it seems that Microsoft [have no plans to provide a static library](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/3434070-statically-link-openmp-vcomp-dll).

-O3 is usually faster than -O2 (and hence -Os), but not always. It may be worth testing both to see what differences you get.

**Comment by BlackIkeEagle** [comment]
@animetosho thank you very much for the explanation. My conclusion from this is, par2.exe wil be ~1.5Mb and in the end I don't think users will run out of diskspace because of it.

The final size of the par2.exe file differs ~100Kb using differnt -O flags, so I'll stick with -O3

I'd rather not use upx on the binaries

**Comment by Safihre** [comment]
👍
