### ISSUE TITLE
Perform verification multithreaded

### ISSUE THREAD

**Issue by Safihre** [Parchive/par2cmdline#95]
I have been testing par2cmdline 0.7.0 in the hopes to get rid of `par2tbb` for SABnzbd (https://github.com/sabnzbd/sabnzbd/issues/902). 
However, `par2tbb` is still faster to repair mainly because it also performs the verification in parallel (test-results below).
Would it be possible to also have the verification multithreaded? I tried to do this myself, but I am a C-noob so I failed.
To avoid unnecessary disk-strain (you mentioned this concern before) one could implement the `-t` parameter similar to `par2tbb`?
```
  -t<+<n>|0<n>|-<n>>: Threaded processing. The options are:
     -t+ to checksum and create/repair concurrently - uses all available logical CPUs - good for hard disk files - [default]
     -t0 to checksum serially but create/repair concurrently with all available logical CPUs - better for slow media such as CDs/DVDs
     -t- to checksum/create/repair serially - uses a single logical CPU - good for testing this program
     -t+n to checksum and create/repair concurrently - uses n logical CPUs (up to all of the available logical CPUs)
     -t0n to checksum serially but create/repair concurrently - uses n logical CPUs if n > 0, or all available CPUs minus n if n < 0
     -t-n to checksum and create/repair concurrently - uses available logical CPUs minus n, eg, -t-1 on a 6 CPU system will use up to 5 CPUs
```
------
Test system: Core i5-4200 @ 2.30Ghz (2 cores, 4 threads), 12GB memory and all data on a fast SSD.

I used a dataset of 2GB with 42 missing articles throughout the download, what usually happens on usenet and ran the test twice for each program:

**par2cmdline 0.6.13 (only x86):**
1: `TotalSeconds      : 87.6838234`
2:  `TotalSeconds      : 86.2515236`

**par2cmdline 0.7.0 (x64):**
1: `TotalSeconds      : 61.612304`
2:  `TotalSeconds      : 60.4033289`

**par2tbb (x64):**
1: `TotalSeconds      : 49.0121549`
2:  `TotalSeconds      : 51.4033289`

**That's still pretty substantial.. But:**

### **Hypothesis:** par2cmdline 0.7.0 doesn't use multithreading to do verification, so the biggest difference is there.
Let's test verification only:

**par2cmdline 0.6.13 (only x86):**
1: `TotalSeconds      : 20.8311689`
2:  `TotalSeconds      : 20.9405503`

**par2cmdline 0.7.0 (x64):**
1: `TotalSeconds      : 19.0471533`
2:  `TotalSeconds      : 19.0547957`

**par2tbb (x64):**
1: `TotalSeconds      : 7.6788562`
2:  `TotalSeconds      : 7.5353623`

### There is a 13 second difference in the verification, which is more than the ~10 seconds difference observed in the full repair!

**Comment by jkansanen** [comment]
I started work on such version, first version works but needs more work.

par2 create with sata3 ssd:

**0.7 - testing:**

real     3m10.520s
user     9m21.802s
sys      0m18.420s

**0.7:**

real     3m47.845s
user     9m19.010s
sys      0m18.194s

**Comment by Safihre** [comment]
@jkansanen That would be for create, but I was wondering more for par2-verify? :)

**Comment by thezoggy** [comment]
@jkansanen any plans to make a new tbb version based off 0.7.0 or better yet.. submit the cuda/tbb code to this project to get included?

**Comment by jkansanen** [comment]
Also applies to verify, with same fileset (that was used with create test) 82 vs 40 sec.

**Comment by Safihre** [comment]
@jkansanen @BlackIkeEagle Any news on this possibly? :)

**Comment by jkansanen** [comment]
@Safihre 
I've been busy with other projects but i should've working version by this week. I'll keep you updated...

**Comment by thezoggy** [comment]
@jkansanen just checking for an update on this one

**Comment by jkansanen** [comment]
OK, there was more work than expected but check out 'mttesting' branch...

Some notes:

- to get any performance gains you need >1 source files, AFAIK you can't parallelize md5 hashing.

- use -T to set how many files are processed in parallel (now defaults to 2 because of "make check" tests)

- using large amount of threads with HDDs could result in trashing and bad performance. It's possible this could be optimized with larger buffers but i've not done testing on it.

Some benchmarks on SATA3 ssd:

**mttesting verify -T4 vs 0.7.3:**
4.6s vs. 15s

**mttesting repair -T4 vs 0.7.3:**
17.2s vs 42.6s

**Comment by Safihre** [comment]
2 sounds like a good default, not to overload the non-SSD. 
Could consider making the `-t` switch like par2tbb to also control verification behavior?

**Comment by jkansanen** [comment]
@Safihre IMO that syntax if confusing and you can use -t and -T to acheive most of that functionality.

**Comment by Safihre** [comment]
@jkansanen Yeah that's true!

**Comment by Safihre** [comment]
Tested it and works great,
```
TotalSeconds      : 8.1542719
```
to
```
TotalSeconds      : 5.0104689
```
Does it also scan 'extra files' multi-threaded?

**Comment by jkansanen** [comment]
@Safihre 
Yes, mt scanning/verifying should be working in all cases

**Comment by Safihre** [comment]
Cool!
So, merge and release? 🥇

**Comment by Safihre** [comment]
I would suggest changing the help-text, it's a bit unclear now:
```
Number of files processed in parallel (2 default) used when can't parallelize otherwise
```
To:
```
Number of files processed in parallel (2 default) during verification
```

**Comment by Safihre** [comment]
For reference another test in which I verified a 19GB set with several missing blocks twice for each program. Results are in seconds.
Windows 10 x64, dual-core i5 2.4Ghz (4 threads), 12GB memory, Samsung EVO 500GB SSD

----

**par2cmdline 0.7.new with -T4**
66.0355151
65.1757379

**par2cmdline 0.7.new with default -T2**
105.0293533
104.4812738

**par2tbb**
72.6985048
71.9074445

**Multipar**
78.7123733
76.9058201

**par2cmdline 0.7.3**
136.7291259
130.8391096

**Comment by BlackIkeEagle** [comment]
Thanks for testing @Safihre . Those results look nice, thanks for the great work @jkansanen

**Comment by BlackIkeEagle** [comment]
@jkansanen if you feel like this is sufficiently stable, could you create a pull request from your sidebranch to master?

**Comment by Safihre** [comment]
There is something strange, which I noticed before and just tested on 2 computers:
_par2cmdline 0.7.4_
130.0539847
129.2835694

_par2cmdline.new with default -T2_
103.2914622
100.5569654

**But:**
_par2cmdline.new with -T1_
168.244667
171.1092582

So setting it to only 1 threaded verify is significantly slower than the original? 
@jkansanen Why would that be?

**Comment by jkansanen** [comment]
@Safihre 
Thanks for testing. I tested 0.7.4 vs -mttesting with -T1 and found no noticable differences in verify, repair and repair with extrafiles (linux 4.12 / gcc 7.2). Could you recheck your results and also try with -q option and provide more info on your test set if possible.

If you're using windows it could be some scheduler issue because of num_threads(1), but the difference between 130 vs 170sec seems large...

**Comment by jkansanen** [comment]
@BlackIkeEagle There's a issue with tests because currently there's two code paths for printing progress line (and related stuff) when OpenMP is used. There's one for -T1 which is identical to non-OpenMP version and slightly different printing when -T2 or larger is used, the difference is cosmetic. I left it there if there's some frontend etc. expecting certain output. Easiest solution would be only to use the new >= -T2 printing for OMP.

**Comment by Safihre** [comment]
Could it be the way the Windows version is compiled? Suboptimal perhaps?
The difference stays in repeated measures, also interleaving old and new versions to make sure it's not some tuning of processor. 
The test set was a 19GB fileset with a few blocks missing throughout the files. What can be expected of a regular usenet post. Have to get a new one now, deleted that one since then.

**Comment by Safihre** [comment]
Aa @jkansanen problem found! Seems the version that was made on AppVeyor using `msbuild` is slower than the `mingw32` version that is created using @BlackIkeEagle's method here in the repo.

**par2 0.7.4 (mingw32)**
TotalSeconds      : 142
TotalSeconds      : 144

**par2-mttesting (msbuild)**
TotalSeconds      : 105
TotalSeconds      : 103

**par2-mttesting (msbuild) `-T1 -q -q`**
TotalSeconds      : 194
TotalSeconds      : 189

**par2-mttesting (mingw32) `-T1 -q -q`**
TotalSeconds      : 145
TotalSeconds      : 143

**Comment by thezoggy** [comment]
others have noticed this sort of issue:
https://github.com/OpenRA/OpenRA/issues/8153

the fix was to move off appveyor and back to travis ci.

**Comment by BlackIkeEagle** [comment]
@thezoggy does travis do windows?

**Comment by Safihre** [comment]
No, but with Mono they managed to do it, just like you do with MingW32 :)

**Comment by BlackIkeEagle** [comment]
@jkansanen I don't think that its a big issue to make the output uniform between -T1 and -T2 or is sabnzbd for example depending on the output of par2 @Safihre ?

if not I would just make the -T1 output look like the new format of -T2

**Comment by Safihre** [comment]
All we care is the `Target: "xxx.r32" - found.` line, and these are printed atomic so that should be fine.
Just keep the code as simple as possible 👍

**Comment by jkansanen** [comment]
@Safihre 
I pushed some slight performance optimization to -mttesting branch, if you wan't to do some testing. 

I tested it with sata3 ssd and "worst-case fileset". There was 1m25s -> 1m9s improvement, with "best-case fileset" there was no difference.

**Comment by Safihre** [comment]
@jkansanen I tried the new version and found around a 1-5% speed-up when I used my usenet-like fileset for testing. All bits help 👍 

Code looks also much cleaner without that special `-T1` code 🎉

**Comment by jkansanen** [comment]
@Safihre Thanks for testing.

**Comment by BlackIkeEagle** [comment]
@jkansanen If you think its good enough, could you create a PR from the branch, then we can go and release 0.8.0

**Comment by krispytom** [comment]
will this work on arm cpus for tablets and phones?

**Comment by krispytom** [comment]
production ready?

**Comment by BlackIkeEagle** [comment]
@krispytom you could help by testing and verifying you have no unexpected behaviour. I've had no issues so far but that is only one usecase

**Comment by Safihre** [comment]
All tests I performed it was always stable.

Hoping for a new official release soon so I can push to the sabnzbd users :)

**Comment by krispytom** [comment]
did testing and haven't seen any issues either. great work

**Comment by Safihre** [comment]
So can we get a release? 🥇

**Comment by BlackIkeEagle** [comment]
Since 0.8.0 is released this can be closed :)
