### ISSUE TITLE
par2cmdline-0.7.0.tar.xz test-driver symlink escapes source root

### ISSUE THREAD

**Issue by jcfp** [Parchive/par2cmdline#98]
The xz-compressed tarball for release 0.7.0 contains the following symlink escaping the source root, also earning it a [lintian hit](https://lintian.debian.org/tags/source-contains-unsafe-symlink.html):
`test-driver -> /usr/share/automake-1.15/test-driver`

**Comment by BlackIkeEagle** [comment]
Will be fixed in 0.7.1

**Comment by BlackIkeEagle** [comment]
0.7.1 is released, the tarballs should be fixed

**Comment by jcfp** [comment]
:thumbsup:
